import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Footer from "@/components/molecules/Footer";
import Navbar from "@/components/molecules/Navbar";
import SignModalManager from "@/components/organisms/SignModalManager";
import RegisterModalManager from "@/components/organisms/RegisterModalManager";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`overflow-x-hidden overflow-y-auto max-w-[100dvw] ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <SignModalManager />
        <RegisterModalManager />
        {children}
        <Footer />
      </body>
    </html>
  );
}
